[build]
  base = "apps/web"       
  command = """
    pnpm install --filter ./packages/*
    pnpm --filter "./packages/*" run build
    pnpm install --filter web
    pnpm --filter web run build
  """
  publish = "apps/web/dist"
