[build]
  base = "."       
  command = """
    pnpm install --filter ./packages/*
    pnpm --filter "./packages/*" run build
    pnpm install --filter web
    pnpm --filter web run build
  """
  publish = "apps/web/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
